### ISSUE TITLE
Feature #1: User can search for place.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can use the app's API to search for places and view the image results of the keywords they search for.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Use the DOM Tree to list the image results of keywords retrieved using the API on the page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/68725614/114634819-34c0ef00-9c78-11eb-9ddd-0b8728bbb279.png)
![image](https://user-images.githubusercontent.com/68725614/114634831-3ee2ed80-9c78-11eb-8c67-5f95246c3ef5.png)

![image](https://user-images.githubusercontent.com/68725614/114634845-499d8280-9c78-11eb-9d70-9abec39de0b9.png)
![image](https://user-images.githubusercontent.com/68725614/114634862-5621db00-9c78-11eb-875d-217152813d74.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create header include the app name and search icon and footer include three icons.
- [x] Add text content and an image on the main page. Also, create a search bar and a button.
- [x] Listen for the ‘click’ events on each icon in the header and footer.
- [x] Listen for the ‘click’ events on the search button to go to the ‘Where are your places’.
- [x] Listen for the ‘click’ events on the ‘To My Place’ button to go to the ‘My Places’ page.
- [x] Add an input type ‘search’ in the search label.
- [x] Ensure to check that you can get the result value for the search term.
- [x] Create a DOM Tree to display search results.
- [x] Listen for the 'submit' events on the search icon form.
- [x] Add a loop to get pictures from the search keyword results.
- [x] Ensure to check the page looks nice and clean (same as work-frame) on both mobile and desktop-sized screens.
- [x] Remove all CSS styling that had no effect or unnecessary.
- [x] Test all functions once more in a private browsing session, and fix all errors if found.
