### ISSUE TITLE
User can save a picture to the album.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/ajax-project#2]
## 📐 Plan

To save a photo, press the Save button to call up the form and store it on the 'My Places' page.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/68725614/108975500-68e63f00-763b-11eb-9917-831e38297082.png)

## ✅ Task List

- [ ] Add a div [data-view = “entry-form”] to the HTML.
- [ ] Listen for 'submit' events on the plus button to bring up a form that has ‘name’, and ‘description’ inputs.
- [ ] Make all inputs of the picture form ‘required’.
- [ ] Listen for ‘submit’ events on the 'Add this place' button.
- [ ] Check your page looks nice and clean on both mobile and desktop-sized screens.
- [ ] Verify that new pictures are saved to my storage.
- [ ] Remove all CSS styling that had no effect or unnecessary.
- [ ] Test all functions once more in a private browsing session, and fix all errors if you have them.
