### ISSUE TITLE
Feature #2: User can save a picture.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can select images they have searched for and save them to their own albums.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a modal that responds to click event listener and store the submit photos from 'form' to my album page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/68725614/114954436-7041f180-9e0f-11eb-8791-ef31c45352ab.png)
![image](https://user-images.githubusercontent.com/68725614/114954459-7d5ee080-9e0f-11eb-8082-15a184c55f68.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make a modal structure with a form element in the HTML.
- [x] Make all inputs of the picture from ‘required’.
- [x] Listen for the ‘click’ events on the plus button to bring up a modal form that has ‘name’, and ‘description’ inputs.
- [x] Listen for the ‘submit’ events on the ‘Add this place’ button.
- [x] Ensure to check that the page looks nice and clean on both mobile and desktop-sized screens.
- [x] Verify that new pictures are saved to my storage.
- [x] Remove all CSS styling that had no effect or unnecessary.
- [x] Test all functions once more in a private browsing session, and fix all errors if found.
