### ISSUE TITLE
User can view saved images.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/ajax-project#3]
## 📐 Plan

Create a personal album page where users can archive previously saved pictures.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/68725614/108977471-6ab10200-763d-11eb-8b4d-e343e6e1904d.png)
![image](https://user-images.githubusercontent.com/68725614/108977506-74d30080-763d-11eb-9e72-003b6089731a.png)

## ✅ Task List

- [ ] Add a div [data-view = “entry-form”] to the HTML.
- [ ] Create a DOM tree function that takes a single image and intro for the picture.
- [ ] Add a loop to create a DOM tree for each picture and append it to the page.
- [ ] Check your album looks nice and clean on both mobile and desktop-sized screens.
- [ ] Remove all CSS styling that had no effect or unnecessary.
- [ ] Test all functions once more in a private browsing session, and fix all errors if you have them.
