### ISSUE TITLE
User can edit a saved picture.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/ajax-project#4]
## 📐 Plan

Allow users to delete an entry from its edit screen.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/68725614/109046725-edf84500-7689-11eb-80a5-8e1f2e2c109e.png)
![image](https://user-images.githubusercontent.com/68725614/109046792-ffd9e800-7689-11eb-80a2-eb386ae33ae5.png)

## ✅ Task List

- [ ] Add rendering function to include an edit icon for each album picture.
- [ ] Listen for clicks on the 'edit icon' to show up the edit form if that icon was clicked.
- [ ] Update the album form's submits handler function to add a new edited object.
- [ ] Remove all CSS styling that had no effect or unnecessary.
- [ ] Test all functions once more in a private browsing session, and fix all errors if you have them.
