### ISSUE TITLE
User can delete a saved picture.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/ajax-project#5]
## 📐 Plan

Allow users to delete a picture from the album list.

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/68725614/109049908-a673b800-768d-11eb-8d8d-a951c92dc1d5.png)
![image](https://user-images.githubusercontent.com/68725614/109050987-e38c7a00-768e-11eb-8036-6ffe28e85caf.png)

## ✅ Task List

- [ ] Listen for clicks on 'Delete icon' to shows a Delete modal when the user clicks that icon.
- [ ] Hide the modal if the user clicks the Cancel button.
- [ ] Remove the entry from the data model and the entry's DOM tree from the page if the user clicks the Delete button.
- [ ] Show the rest of the Album list if the user clicks Delete.
- [ ] Remove all CSS styling that had no effect or unnecessary.
- [ ] Test all functions once more in a private browsing session, and fix all errors if you have them.
