### ISSUE TITLE
Feature #3: User can view saved images.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can view images they have saved on the album page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create DOM Tree for the album page and render it, so user can see their saved image where they submitted through the 'form'.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/68725614/115090988-2585af80-9ecb-11eb-803f-67d8a469d10a.png)
![image](https://user-images.githubusercontent.com/68725614/115091012-359d8f00-9ecb-11eb-9285-d478f545539d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a div [data-view = “album-page”] to the HTML.
- [x] Create a DOM tree function that takes a single image and intro for the picture.
- [x] Add a loop to create a DOM tree for each picture and append it to the page.
- [x] Add an edit icon next to the name label
- [x] Ensure to check that album looks nice and clean on both mobile and desktop-sized screens.
- [x] Remove all CSS styling that had no effect or unnecessary.
- [x] Test all functions once more in a private browsing session, and fix all errors if found.
