### ISSUE TITLE
Feature #4: User can edit saved images.

### ISSUE THREAD

**Issue by SeungjooKimSJ** [SeungjooKimSJ/ajax-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can modify the image name and description on the album page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create a modal form that responds to click event listener on the edit icon, so the user can edit the saved image's name and description.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/68725614/115601636-e4a6e580-a292-11eb-9dce-c03ed15a3cdd.png)
![image](https://user-images.githubusercontent.com/68725614/115601728-fbe5d300-a292-11eb-99bd-6ed2d0306538.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a modal form that responds to the edit icon and makes it hidden.
- [x] Listen for the ‘click’ events on the edit icon to show up the edit modal form.
- [x] Add a ‘submit’ event handler function to add a new edited object.
- [ ] Listen for the ‘submit’ events on the save button to update the album information.
- [ ] Remove all CSS styling that had no effect or unnecessary.
- [ ] Test all functions once more in a private browsing session, and fix all errors if found.
